package Lexer;

public enum TokenType {
    SEMICOLON,

    LET, CONST, INTEGER, STRING, IDENTIFIER,
    TRUE, FALSE, NULL,

    PLUS, MINUS, STAR, FORSLASH, PLUSPLUS, MINUSMINUS,
    PLUSEQUAL, MINUSEQUAL, STAREQUAL, FORSLASHEQUAL, EQUAL,

    DEQUAL, LESSERTHAN, GREATERTHAN, LESSERTHANEQU, GREATERTHANEQU, BANG, BANGEQUAL,

    LEFTPAR, RIGHTPAR
}
