package Lexer;

public enum TokenType {
    SEMICOLON,

    INTEGER, STRING, IDENTIFIER,
    TRUE, FALSE, NULL,

    PLUS, MINUS, STAR, FORSLASH, PLUSPLUS, MINUSMINUS,
    PLUSEQUAL, MINUSEQUAL, STAREQUAL, FORSLASHEQUAL, EQUAL,
    AND, OR, QUESTIONMARK, COLON,

    DEQUAL, LESSERTHAN, GREATERTHAN, LESSERTHANEQU, GREATERTHANEQU, BANG, BANGEQUAL,

    LEFTPAR, RIGHTPAR, LEFTBRACE, RIGHTBRACE,

    LET, CONST, PRINT, IF, ELSE
}
